version: "3.8"

services:
  # Base de Datos Relacional (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: flight_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: flight_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flight_network

  # Redis para control de concurrencia
  redis:
    image: redis:7-alpine
    container_name: flight_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flight_network

  # Backend (NestJS + Prisma)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flight_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@postgres:5432/flight_booking?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - flight_network

  # Frontend (Angular servido con Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flight_frontend
    restart: always
    ports:
      - "4200:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - flight_network

volumes:
  postgres_data:

networks:
  flight_network:
    driver: bridge
